### ISSUE TITLE
Unable to remove permission bug

### ISSUE THREAD

**Issue by iaincrawf** [linn/authorisation#33]
Can't remove product.hold permission from myself, not sure if it's cause I'm removing it from myself or if it's buggy for removing them from anyone

**Comment by RossStewart** [comment]
Dove into this and spoke through it with Lewis. Basically, the reason that we are able to delete SOME privileges but not all is due to the way the privileges have been assigned. Assigning a individual privileges to a user and deleting it is totally fine, however it's the privileges that have been assigned to a user due to being assigned through a group that are the ones that are causing the problem. They ultimately are individual permissions but we're not able to retrieve/delete them due to the group.

Ideally, we'd do something like display the user and which groups they are part of with a small list of privileges that are associated with them due to these and then have a further column with additional privileges. Going to take that line out whilst we discuss it.

**Comment by iaincrawf** [comment]
Ahhh yeah that makes perfect sense, we can just unassign people from the group for those cases then! Would just be good to make the app clearer where the privileges come from in that case. I think we'll also want to add in a similar line "does priv.id == priv.id" to the removeFromGroup method linq query btw, to make sure we remove the right priv from a group if & not the first if we ever remove privs from a group @RossStewart
