### ISSUE TITLE
Alphabetically sort all lists and dropdowns on front end

### ISSUE THREAD

**Issue by iaincrawf** [linn/authorisation#53]
Noticed on groups when actually using it, becomes a pain to find things and compare to other screens because nothing is in alphabetical order. Same when viewing privileges for an individual
![image](https://user-images.githubusercontent.com/51612225/137316451-7e727333-d723-4e6b-bc3a-09c9aade3fab.png)
![image](https://user-images.githubusercontent.com/51612225/137315906-c9aae1c7-ad41-4f29-ba20-b5eac4e48f37.png)
![image](https://user-images.githubusercontent.com/51612225/137315946-ea4c6603-2632-4a93-892e-31f57cdaa4e8.png)

**Comment by RossStewart** [comment]
I ended up sorting this in the PrivilegeService rather than the front end as I felt it was a bit cleaner. To do it in the front end I would have had to transfer the data to a new "sorted" map as you can't sort an existing map and this is what the front end  React code was using. I figured that the cost of doing this in multiple places (each time we want an ordered list) was outweighed by performing the sorting as close to the data as possible - in this case in the service. Can definitely talk about it though!

**Comment by iaincrawf** [comment]
Will find somewhere in stores we've sorted things as an example of what I meant in case you ever do want to do it on the front end, think you can just .map as it's being displayed, or in the container but that's fine :)
